// apps/react/src/features/createTestCenter/PrevNextComponent.tsx
import { Button } from '@/components/ui/button'

type PrevNextComponentProps = {
  prevHandler: () => void
}

export const PrevNextComponent = ({ prevHandler }: PrevNextComponentProps) => {
  return (
    <div className="space-x-5">
      <Button variant="outline" onClick={prevHandler} type="button">
        Prev
      </Button>
      <Button type="submit">Next</Button>
    </div>
  )
}

// apps/vue/src/features/createTestCenter/PrevNextComponent.vue
<script setup lang="ts">
import Button from '@/components/ui/button/Button.vue';
defineEmits<{
  prev: [];
}>();
</script>
<template>
  <div class="space-x-5">
    <Button variant="outline" @click="$emit('prev')" type="button">Prev</Button>
    <Button type="submit">Next</Button>
  </div>
</template>
